version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web